### ISSUE TITLE
Login does not work (I followed the readme)

### ISSUE THREAD

**Issue by norandom** [kiwiz/411#9] opened 2016-08-22 14:22 UTC
Hey,

I cannot generate a successful login.

I installed 411 on a host and then:

```
:/var/www/411$ sudo sqlite3 data.db < db.sql
:/var/www/411$ sudo bin/create_site.php
Creating new site
Site name: test
Hostname: test
From email: test@test.com
From Error email: test@test.com
Default To email: test@test.com

Site created! ID: 1
marius@rkv-c3s-selks2:/var/www/411$ sudo bin/create_user.php
Creating new user
Username: user
Real name: User User
Password: 
Email: user@test.de
Admin (y/n): n

User created! ID: 1
```

So far, so good. Now I go to the site and voila:

![capture](https://cloud.githubusercontent.com/assets/11855163/17858044/ab3bf096-6873-11e6-9074-7d008662f144.PNG)

I have the distinct feeling that the hostname needs to be correct. Is that so?

I checked out the DB:

```
 sudo sqlite3 data.db
SQLite version 3.8.7.1 2014-10-29 13:59:56

sqlite> .tables
alert_logs      groups          report_targets  search_targets  users
alerts          jobs            reports         searches
config          lists           search_filters  sites
group_targets   meta            search_logs     slogs
sqlite> select * from users;
1|1|user|User User|$2y$10$EvfB6.2XkRcuobAEPnNLKuu5IqLx0BH/aQKXkrkRS9uzmaNcGHy9.|user@test.de|0|{}|0|1471875162|1471875162
```

I keep the hash here since it's obviously just a test in the lab ;). Anyways, I don't get a successful login with this.

**Comment by missnebun** [comment] 2016-08-22 15:15
Hi @norandom . I had the same exact problem. The problem is the hostname part.
You need to add the add the hostname: as the URL that you are accessing 411.
So let's say that your URL: server1.example.com that is what you need to have hostname as server1.example.com.

**Comment by kiwiz** [comment] 2016-08-22 15:42
Yup. Alternatively, you can the `411HOST` Apache environment variable to the same value as the site (so `test` in your case).

**Comment by norandom** [comment] 2016-08-22 15:42
I also changed the default port from 80 to 8081.

If I create a host with `correct_hostname.local` it does not work. If I use `correct_hostname.local:8081` a load screen appears. The credentials are accepted but nothing happens. The loading does not finish, yet does also not consume CPU or memory.

**Comment by kiwiz** [comment] 2016-08-22 15:55
@norandom: Hmm, can you try clearing your cookies and seeing if that works?

**Comment by missnebun** [comment] 2016-08-22 15:56
Can you do me a favor and add the hostname as the ip address of the 411 server and then use as URL the IP address. See if that works.

**Comment by norandom** [comment] 2016-08-22 16:22
@kiwiz that had no effect. I switched the default port to 80 to avoid having the `:port` in the URL.

The error message - cookies have been cleared before the login - is:

` [:error] [pid 26809] [client 127.0.0.1:59468] except [NONE] FOO\\UnauthorizedException: "Invalid nonce specified" at [/var/www/411/phplib/REST.php:101] 0:[FOO\\REST->route() called at [/var/www/411/htdocs/api/login.php:6]], referer: ... http://correct:hostname.local/login`

If I use the hostname instead of the qualified domain name I run into the same issue.

![capture2](https://cloud.githubusercontent.com/assets/11855163/17862282/17eef066-6884-11e6-931e-309218435d02.PNG)

[:error] [pid 26809] [client 127.0.0.1:60754] except [NONE] FOO\\UnauthorizedException: "Invalid nonce specified" at [/var/www/411/phplib/REST.php:101] 0:[FOO\\REST->route() called at [/var/www/411/htdocs/api/login.php:6]], referer: http://correct-hostname/login

I guess I have to debug this a little... At this point I haven't gotten into the code enough to pinpoint where it steps our or why.

**Comment by missnebun** [comment] 2016-08-22 16:30
@norandom take a look at this https://github.com/kiwiz/411/issues/5

**Comment by norandom** [comment] 2016-08-22 17:43
Okay, I can confirm that setting the hostname here fixes the issue.

**Comment by kiwiz** [comment] 2016-08-22 19:08
Great! Going to close this issue since this is now resolved. :]

**Closed by kiwiz** 2016-08-22 19:08 UTC
